title: Shanyi Li
description: Ph.D. Candidate in Computer Science and Engineering at CUHK
baseurl: ""
url: "https://klaysyli.github.io"
github_username: klaysyli

theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
